---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: shopsphere-s3-secrets
  namespace: shopsphere
spec:
  encryptedData:
    AWS_ACCESS_KEY_ID: AgAVmdt3yX11Y9FqH5INRJmtT/xU1CK5CdH60fFlos46Bm2NyjiqIKH2Cg1u3hRuxXoxi2KH3MpbeY4zQ3EObHAfh12bchILeZeR58VFJwD29uIoiTZOgCtkPVTdazSrXThRwDxKOmgfXdLIUBMYLe8lBtEWxVCI8QDBKOyc13aExiOE5Ii34gPz2GCJMdfEfqgpOTzmbQuIjOLD146MdihVYVp6gxpZb4XO+81BivR4llu2llDymBsihImCSv8rm2drfdbQqZLYGcm97lfV60qb6/WVtzDFh9Ae0m/L82SWhzfZyxetqdtJ1K+ysssHEmFf/2mkpxndTKFjvmqfjCjpadddHUz+v9ZXDwKRtuwcFk0kZyYrwfGEZZsIwxm489tGoBYdZ2rYRCa05hppEOY55ugegjQ6FgTVn3K+GodxE6mnhJmTlXFXALZB/vWr7CJbOUfgd/mm1QzlwrSw5rblmxIlZ3ziNaSxRieFuhfAfwxfrq6W5tYCdpYEJyoFCcKAFUhF+TZ5uDFFoHrqdtj0VyVPxZ6PWFnNlx3shixUBypubxkJrWgbOwThUJPqgeK5IA7XYiSz+PGG1KsMOLpMlkUsk8ZjG/enR9anGpPVUpumtYGIUvDQcvVeOLlq1uk+l+SbIXanAMZV59Z/O1hMIKPgSiNZxjxbjtJq6v+megHgQvAn4IRCtF7fVT5C8aLIIidYi/5lSnFuOJHKCkN1XNL8Lw==
    AWS_SECRET_ACCESS_KEY: AgCaRki72FQntE4pdQ68NnlfJ3CbUFpf3ryitmFsSwVNF6lZeRo9M2GZ+DlELdlatat/MiV3TaA8euQJEfra9EtkNS09KJcdgAY+CVsEXMPuo7R+wgmTf54OTGu8hqs08nqDv8fEsZSb0F4yj1uka0vkwEmRRoChU42fOO4SvhYHZffeLyVkizhpNdRET+EXdr6zJg01oJpuNAbM/KqtlL1Mb9HQCYLzyxq8LBiNfU+a393Vx42n+dhYIhVseDxqDBR7QKL61Ef3PvJ1jklMjtI8KytxEYQyTP52mJbh07i5vHkv+7LEc1uQy33xS79f14Oai0thd1d2+HXodoIqWe2LEc+BBI31rlCdJVPA5Olddu+816+i842tOdng/VPzDI3ycOX0kT/TdoK+mw2scKHv6C9A1imCjXRafmLZcm6ZXXe38BS5lcpFYSD7P++K6LdX3MBQBULEJDXl/SbQy0HnEXg80jF7lAr7yO7kR9QyDnD6yuRGagZLS0fqj/74E4vyHZ9Cy+XBZmahoRvpmbZEgEs6DFbP6TwRtZomYfEWAGdhyJ88k0uJrbESKCRishLNtoQaMFICtbFYPU1ehAJrSR2bSb661WNyTXDCpi++EkYJ20XT70KLwvaz0/fbGMqv7jzugtrQW/G4suvY0JTqslutXDWOUTsUntOw3CN8u3uvSGu3sXWwlAeucs3djoe/t8nFsondX76Ix69S+me0jFBYWIcAE/RGNdXJO3R1WzVKXBzEGCaS
  template:
    metadata:
      name: shopsphere-s3-secrets
      namespace: shopsphere
    type: Opaque
