apiVersion: v1
kind: Secret
metadata:
  name: shopsphere-secrets
  namespace: shopsphere
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: RootSecurePassword123!
  MYSQL_DATABASE: shopsphere
  MYSQL_USER: shopsphere
  MYSQL_PASSWORD: StrongPassword123!
  JWT_SECRET: replace-with-a-long-random-string-super-secret-32-chars
  SEED_ADMIN_PASSWORD: "123456"
