apiVersion: batch/v1
kind: Job
metadata:
  name: backend-seed
  namespace: shopsphere
spec:
  backoffLimit: 3
  ttlSecondsAfterFinished: 300
  template:
    spec:
      restartPolicy: Never
      initContainers:
      - name: wait-for-db
        image: mysql:8.0
        command: ['sh', '-c', 'until mysqladmin ping -h $DB_HOST -P $DB_PORT -u $MYSQL_USER -p$MYSQL_PASSWORD; do echo waiting for db; sleep 2; done']
        env:
        - name: DB_HOST
          valueFrom: { configMapKeyRef: { name: shopsphere-config, key: DB_HOST } }
        - name: DB_PORT
          valueFrom: { configMapKeyRef: { name: shopsphere-config, key: DB_PORT } }
        - name: MYSQL_USER
          valueFrom: { secretKeyRef: { name: shopsphere-secrets, key: MYSQL_USER } }
        - name: MYSQL_PASSWORD
          valueFrom: { secretKeyRef: { name: shopsphere-secrets, key: MYSQL_PASSWORD } }
        resources:
          requests: { cpu: "20m", memory: "32Mi" }
          limits: { cpu: "50m", memory: "64Mi" }
      containers:
      - name: seed
        image: princewillopah/shopshere-node-backend:1.2
        imagePullPolicy: IfNotPresent
        command: ["sh", "-c", "npm run seed"]
        env:
        - name: DB_HOST
          valueFrom: { configMapKeyRef: { name: shopsphere-config, key: DB_HOST } }
        - name: DB_PORT
          valueFrom: { configMapKeyRef: { name: shopsphere-config, key: DB_PORT } }
        - name: DB_NAME
          valueFrom: { secretKeyRef: { name: shopsphere-secrets, key: MYSQL_DATABASE } }
        - name: DB_USER
          valueFrom: { secretKeyRef: { name: shopsphere-secrets, key: MYSQL_USER } }
        - name: DB_PASSWORD
          valueFrom: { secretKeyRef: { name: shopsphere-secrets, key: MYSQL_PASSWORD } }
        - name: NODE_ENV
          valueFrom: { configMapKeyRef: { name: shopsphere-config, key: NODE_ENV } }
        - name: SEED_ENABLED
          valueFrom: { configMapKeyRef: { name: shopsphere-config, key: SEED_ENABLED } }
        - name: SEED_ADMIN_NAME
          valueFrom: { configMapKeyRef: { name: shopsphere-config, key: SEED_ADMIN_NAME } }
        - name: SEED_ADMIN_EMAIL
          valueFrom: { configMapKeyRef: { name: shopsphere-config, key: SEED_ADMIN_EMAIL } }
        - name: SEED_ADMIN_PASSWORD
          valueFrom: { secretKeyRef: { name: shopsphere-secrets, key: SEED_ADMIN_PASSWORD } }
        - name: PLACEHOLDER_IMAGE_URL
          valueFrom: { configMapKeyRef: { name: shopsphere-config, key: PLACEHOLDER_IMAGE_URL } }
        - name: STORAGE_PROVIDER
          valueFrom: { configMapKeyRef: { name: shopsphere-config, key: STORAGE_PROVIDER } }
        resources:
          requests: { cpu: "100m", memory: "128Mi" }
          limits: { cpu: "300m", memory: "512Mi" }