global:
  environment: dev


config:
  NODE_ENV: development

  CORS_ALLOWED_ORIGINS: "*"

  SEED_ENABLED: "true"


backend:
  replicaCount: 1


frontend:
  replicaCount: 1


mysql:
  enabled: true

  pdb:
    enabled: false


autoscaling:
  backend:
    enabled: false

  frontend:
    enabled: false


podDisruptionBudget:
  backend:
    enabled: false

  frontend:
    enabled: false


ingress:
  enabled: true
  className: nginx
  host: shopsphere.local


migration:
  enabled: true


seed:
  enabled: true