global:
  environment: staging


config:
  NODE_ENV: staging

  CORS_ALLOWED_ORIGINS: "*"

  SEED_ENABLED: "false"


backend:
  replicaCount: 2


frontend:
  replicaCount: 1


mysql:
  enabled: true

  pdb:
    enabled: true
    maxUnavailable: 0


autoscaling:

  backend:
    enabled: true

    minReplicas: 2
    maxReplicas: 5

    metrics:
      cpu:
        enabled: true
        averageUtilization: 70

      memory:
        enabled: true
        averageUtilization: 80

  frontend:
    enabled: true

    minReplicas: 1
    maxReplicas: 3

    metrics:
      cpu:
        enabled: true
        averageUtilization: 70


podDisruptionBudget:

  backend:
    enabled: true
    minAvailable: 1

  frontend:
    enabled: true
    minAvailable: 1


ingress:
  enabled: true
  className: nginx
  host: shopsphere-staging.example.com


migration:
  enabled: true


seed:
  enabled: false