apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: shopsphere
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 101
        runAsGroup: 101
      containers:
      - name: frontend
        image: princewillopah/shopsphere-node-frontend:1.3
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
          name: http
        resources:
          requests: { cpu: "50m", memory: "64Mi" }
          limits: { cpu: "200m", memory: "128Mi" }
        readinessProbe:
          httpGet: { path: /, port: http }
          initialDelaySeconds: 5
        livenessProbe:
          httpGet: { path: /, port: http }
          initialDelaySeconds: 10
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities: { drop: ["ALL"] }
        volumeMounts:
        - name: tmp-volume
          mountPath: /tmp
      volumes:
      - name: tmp-volume
        emptyDir: {}
