# -------------------------------------
# Stage 1: Build & Dependencies
# -------------------------------------
FROM node:20-alpine AS build
WORKDIR /app
COPY package*.json ./
# COPY package-lock.json* ./

# if lock exists use ci, if not use install
RUN if [ -f package-lock.json ]; then npm ci; else npm install; fi
COPY . .
RUN npm run build


# -------------------------------------
# Stage 2: Final Lightweight Runtime
# -------------------------------------
FROM nginx:alpine
COPY --from=build /app/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf
# RUN addgroup -S appgroup && adduser -S appuser -G appgroup && chown -R appuser:appgroup /usr/share/nginx/html

## nginx needs to run as non-root in K8s
RUN chown -R nginx:nginx /usr/share/nginx/html /var/cache/nginx /var/run
USER nginx
EXPOSE 8080
