apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: shopsphere
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend  # must match selector.matchLabels
    spec:
      # 1. SECURITY - pod level
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000   # 1000 is the default UID for the 'node' user
        runAsGroup: 1000  # 1000 is the default GID for the 'node' group
        fsGroup: 1000     # Ensures any mounted volumes are readable by 'node
        seccompProfile: { type: RuntimeDefault }

      # 2. GRACEFUL SHUTDOWN - what should happen
      terminationGracePeriodSeconds: 30 # gives Node 30s to close DB connections before SIGKILL -  # WHAT HAPPENS: K8s waits 30s for Node to close DB pools before SIGKILL

      initContainers: # WHAT HAPPENS: runs BEFORE app, must succeed. If DB not ready, pod stays Init:0/1
      - name: wait-for-db
        image: mysql:8.0

        # command here OVERRIDES Dockerfile ENTRYPOINT
        command: ['sh', '-c', 'until mysqladmin ping -h $DB_HOST -P $DB_PORT -u $MYSQL_USER -p$MYSQL_PASSWORD; do echo waiting for db; sleep 2; done']
        env:
        - name: DB_HOST
          valueFrom: { configMapKeyRef: { name: shopsphere-config, key: DB_HOST } }
        - name: DB_PORT
          valueFrom: { configMapKeyRef: { name: shopsphere-config, key: DB_PORT } }
        - name: MYSQL_USER
          valueFrom: { secretKeyRef: { name: shopsphere-secrets, key: MYSQL_USER } }
        - name: MYSQL_PASSWORD
          valueFrom: { secretKeyRef: { name: shopsphere-secrets, key: MYSQL_PASSWORD } }
        resources:
          requests: { cpu: "20m", memory: "32Mi" }
          limits: { cpu: "50m", memory: "64Mi" }

      # 4. MAIN APP
      containers:
      - name: backend
        image: princewillopah/shopsphere-node-backend:1.2
        imagePullPolicy: Always # Never for kind local, IfNotPresent for DockerHub - Never breaks on EKS
        # command / args: If you set them here, they OVERRIDE Dockerfile CMD/ENTRYPOINT
        # Don't set command: ["sh", "-c", "npm start"] - use Dockerfile CMD. Only override for Jobs
        ports:
        - containerPort: 5000
          name: http # default
          protocol: TCP # default

        # 5. CONFIG - injected at runtime
        envFrom:
        - configMapRef: { name: shopsphere-config }
        - secretRef: { name: shopsphere-secrets }
        # mapping because secret has MYSQL_DATABASE but app expects DB_NAME
        env:
        - name: DB_NAME
          valueFrom: { secretKeyRef: { name: shopsphere-secrets, key: MYSQL_DATABASE } }
        - name: DB_USER
          valueFrom: { secretKeyRef: { name: shopsphere-secrets, key: MYSQL_USER } }
        - name: DB_PASSWORD
          valueFrom: { secretKeyRef: { name: shopsphere-secrets, key: MYSQL_PASSWORD } }
        - name: AWS_ACCESS_KEY_ID
          valueFrom: { secretKeyRef: { name: shopsphere-s3-secrets, key: AWS_ACCESS_KEY_ID } }
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom: { secretKeyRef: { name: shopsphere-s3-secrets, key: AWS_SECRET_ACCESS_KEY } }


        # 6. RESOURCES - what should happen: scheduler uses requests to place pod, kubelet kills if limits exceeded
        resources: # WHY: scheduler needs requests for HPA, limits protect node
          requests:
            cpu: "200m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"

        # 7. PROBES - what should happen: kubelet checks these
        readinessProbe: # WHAT HAPPENS: Pod gets NO traffic until this passes
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 15 # App can accept traffic almost immediately
          periodSeconds: 10
          failureThreshold: 3
        livenessProbe: # WHAT HAPPENS: kubelet restarts pod if this fails
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 30  # Verifies the container is up quickly
          periodSeconds: 20
          failureThreshold: 3

        # 8. SECURITY - container level - Restricts what the container can do to the system
        securityContext:
          allowPrivilegeEscalation: false # Prevents processes from gaining more privileges than their parent
          readOnlyRootFilesystem: true # # Set to true only if your app doesn't write local logs/tmp files - your app can't write to container FS, must use volume if needs tmp
          capabilities: { drop: ["ALL"] }

        volumeMounts:
        - name: tmp
          mountPath: /tmp

      volumes:
      - name: tmp
        emptyDir: {}

      # 9. PLACEMENT - for HA later
      # affinity:
      #   podAntiAffinity:
      #     requiredDuringSchedulingIgnoredDuringExecution:
      #     - labelSelector: { matchLabels: { app: backend } }
      #       topologyKey: kubernetes.io/hostname