{{- if .Values.frontend.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "shopsphere.frontend.fullname" . }}
  labels:
    {{- include "shopsphere.frontend.labels" . | nindent 4 }}

spec:
  replicas: {{ .Values.frontend.replicaCount }}

  selector:
    matchLabels:
      {{- include "shopsphere.frontend.selectorLabels" . | nindent 6 }}

  template:
    metadata:
      labels:
        {{- include "shopsphere.frontend.labels" . | nindent 8 }}
      {{- with .Values.frontend.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}

    spec:
      serviceAccountName: {{ include "shopsphere.serviceAccountName" . }}

      {{- with .Values.frontend.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      {{- with .Values.frontend.securityContext.pod }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      containers:
        - name: frontend

          image: {{- if .Values.frontend.image.digest }}
            "{{ .Values.frontend.image.repository }}@{{ .Values.frontend.image.digest }}"
          {{- else }}
            "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
          {{- end }}

          imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}

          ports:
            - name: http
              containerPort: {{ .Values.frontend.container.port }}
              protocol: TCP

          resources:
            {{- toYaml .Values.frontend.resources | nindent 12 }}

          {{- if .Values.frontend.probes.readiness.enabled }}
          readinessProbe:
            httpGet:
              path: {{ .Values.frontend.probes.readiness.path }}
              port: {{ .Values.frontend.probes.readiness.port }}
            initialDelaySeconds: {{ .Values.frontend.probes.readiness.initialDelaySeconds }}
            periodSeconds: {{ .Values.frontend.probes.readiness.periodSeconds }}
            timeoutSeconds: {{ .Values.frontend.probes.readiness.timeoutSeconds }}
            successThreshold: {{ .Values.frontend.probes.readiness.successThreshold }}
            failureThreshold: {{ .Values.frontend.probes.readiness.failureThreshold }}
          {{- end }}

          {{- if .Values.frontend.probes.liveness.enabled }}
          livenessProbe:
            httpGet:
              path: {{ .Values.frontend.probes.liveness.path }}
              port: {{ .Values.frontend.probes.liveness.port }}
            initialDelaySeconds: {{ .Values.frontend.probes.liveness.initialDelaySeconds }}
            periodSeconds: {{ .Values.frontend.probes.liveness.periodSeconds }}
            timeoutSeconds: {{ .Values.frontend.probes.liveness.timeoutSeconds }}
            successThreshold: {{ .Values.frontend.probes.liveness.successThreshold }}
            failureThreshold: {{ .Values.frontend.probes.liveness.failureThreshold }}
          {{- end }}

          {{- with .Values.frontend.securityContext.container }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}

          {{- if .Values.frontend.tmpVolume.enabled }}
          volumeMounts:
            - name: tmp
              mountPath: {{ .Values.frontend.tmpVolume.mountPath }}
          {{- end }}

      {{- if .Values.frontend.tmpVolume.enabled }}
      volumes:
        - name: tmp
          emptyDir: {}
      {{- end }}

      {{- with .Values.frontend.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      {{- with .Values.frontend.topologySpreadConstraints }}
      topologySpreadConstraints:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      {{- with .Values.frontend.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      {{- with .Values.frontend.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}