---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgBdl8HXdDEW7GAKrGlH1XjVQgU8plpZ9RyYnQ61dl8dnTPb4v4IqVdS6XwmNQw4lk7SVXFhFHmzq0PYplrj0EJ8qwTW2mFRXOEo4J5GJcA1j8lb/V2ERJPk/rUNmHkian4PZyWxZQVYOj19BBPvCKnmuZCuyCG0Cu3D9v0NHgPeT5USylaDhAGekAeeCQVYR7rAWhubmKpKnl2U0yW1RbyRFxsl8Ea4Dw3zmTnKjfbGolDGl6XQfx/9O4KB/1sS17Yk3FlKYfF1Se0gtlz8kBxJR+Ad5Xqg9SF8LXnHUDMvWtlKsUiMrREumquVI364nbHQiGqM2e+TjvrRy3mGgcC/Hn3P14n7LW4fEIbdSohfNEGESVs8PrGtXuNZ2155BNpW+zJzRHIZGMzTsCcv3Lr4sPoufAmndGqoP7Dr0RQV+cTBNv+BZc89ngrl/XcFCu1kW1Jdd5QvjSEvyITFTb+0wWW5i5qymFtXUeWViYq7hzadEwOdJwzT8vlr7bYhPExK6raX62nNfoInT4C9khe885aRXpWju0wXRZ9nY7WxZwZaYnw4LJtNsdssYj48/an+Hl5ckxFGnr/tic6KoxYIy85PDljnun0wxneyYOQHAaPmaUX8wmWQ1CxL2C19TjuzqFEItTQ45OqQOd6rBcbaTaS3ltsRsr9QQU2creZ7criesIduXq6kPzMREwVD/XUvH1XyVVU=
    admin-user: AgAv4rrYzDkBn4ERxXCK51qnaPJExJjjrwklD2RXtX8/niXGL5iIQ5xBo/ebXYH71Nuo1wEx1LKJ0FPc9LDuF+WWTn6DHoscDVEO8cnBabplWxx8QEBPC7NDcS/8rZq+6VVxjBjULKOyfTkM4tG0YjLJvPsDpDLG4hTVZYkYF1jn/0hL4033rGRntN6Xc7TpANgOFA733XgrtNVCwQxex4vF6xNZyr1GeXeEVW+QjQgbthLvvn9kdSv/hfuXUavUnOVNg66C6hCiDzgQixuQzs7bjwJ3E5xCql3FAaRP2B6V4YRtuV55Xa+1gsSGqf2k2Bu2TfaCs09EzReir6ceAOJrZL8a4f/bNulsy4T4DnD9GBqHBPJ9ovckxI+19gj5CHsN5FOGtUxvUpFdqeqK3AWBbkYJDsGlSZBrJmo4QZG48r2gofitpwihH/Y7FZWXTNSY4rqwRdpXaZO9wkrc8ary7QobSuj4xeUB5TJzMMFJnev4KmSHO/F8feI6Go5sZXtQE11l42vZX7N648dNfZwsXUFgg1qQJSVTIAwOJFaOEcDv2NdLOuBIT60LeMkjYVkEXiB1C8DtZHPlZs+YZowEuhYzG50z6EItQayGR0WS5AQEBe6OhS2Xk/c+bpDnKF542Jc2B6lVHIeFqbT0fBYMfd2hGX7N/Gb7HgtAYV9gmFAyHgCYDwEehsMgzYS2gsvxZWvvAw==
  template:
    metadata:
      name: grafana-admin
      namespace: monitoring
    type: Opaque
