{{- if .Values.backend.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "shopsphere.fullname" . }}-config
  labels:
    {{- include "shopsphere.backend.labels" . | nindent 4 }}
data:
  DB_HOST: {{ .Values.config.DB_HOST | quote }}
  DB_PORT: {{ .Values.config.DB_PORT | quote }}
  DB_NAME: {{ .Values.config.DB_NAME | quote }}
  NODE_ENV: {{ .Values.config.NODE_ENV | quote }}
  SERVER_PORT: {{ .Values.config.SERVER_PORT | quote }}
  JWT_EXPIRATION_MS: {{ .Values.config.JWT_EXPIRATION_MS | quote }}
  CORS_ALLOWED_ORIGINS: {{ .Values.config.CORS_ALLOWED_ORIGINS | quote }}
  MAX_UPLOAD_MB: {{ .Values.config.MAX_UPLOAD_MB | quote }}
  STORAGE_PROVIDER: {{ .Values.config.STORAGE_PROVIDER | quote }}
  S3_BUCKET: {{ .Values.config.S3_BUCKET | quote }}
  AWS_REGION: {{ .Values.config.AWS_REGION | quote }}
  S3_KEY_PREFIX: {{ .Values.config.S3_KEY_PREFIX | quote }}
  S3_PUBLIC_BASE_URL: {{ .Values.config.S3_PUBLIC_BASE_URL | quote }}
  PLACEHOLDER_IMAGE_URL: {{ .Values.config.PLACEHOLDER_IMAGE_URL | quote }}
  SEED_ENABLED: {{ .Values.config.SEED_ENABLED | quote }}
  SEED_ADMIN_NAME: {{ .Values.config.SEED_ADMIN_NAME | quote }}
  SEED_ADMIN_EMAIL: {{ .Values.config.SEED_ADMIN_EMAIL | quote }}
  DB_POOL_MAX: {{ .Values.config.DB_POOL_MAX | quote }}
  OBSERVABILITY_SERVICE_NAME: {{ .Values.config.OBSERVABILITY_SERVICE_NAME | quote }}
  LOG_LEVEL: {{ .Values.config.LOG_LEVEL | quote }}
  METRICS_ENABLED: {{ .Values.config.METRICS_ENABLED | quote }}
  OTEL_ENABLED: {{ .Values.config.OTEL_ENABLED | quote }}
  OTEL_EXPORTER_OTLP_ENDPOINT: {{ .Values.config.OTEL_EXPORTER_OTLP_ENDPOINT | quote }}
{{- end }}