
apiVersion: v1
kind: Secret
metadata:
  name: shopsphere-s3-secrets
  namespace: shopsphere
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: "AKIAU4ABMDTJPVX5RRRV"
  AWS_SECRET_ACCESS_KEY: "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"